### ISSUE TITLE
multi-pass effects

### ISSUE THREAD

**Issue by aferriss** [gre/glsl-transition#17]
Are there any examples of multi-pass effects (2 pass pingpong blur for instance), or this not currently possible in this implementation? 

It looks like there are some attempts at blur effects in the gallery, but nothing that really does a nice soft gaussian blur transition.

**Comment by aferriss** [comment]
I figured out a hacky way to do this, rendering my blur textures outside of glsl-transition and just passing them in as uniforms to an additional shader for composing effects. Essentially you need 4 textures, to, from, blurredTo, & blurredFrom. 


````
shell.on('tick', function(){
	blurFboH.bind();
		blurShaderH.bind();
		blurShaderH.uniforms.srcTex = fromTex.bind();
		blurShaderH.uniforms.step = [1.0/shell.width,1.0/shell.height];
		drawScreen(gl);

	blurFboV.bind();
		blurShaderV.bind();
		blurShaderV.uniforms.srcTex = blurFboH.color[0].bind();
		blurShaderV.uniforms.step = [1.0/shell.width,1.0/shell.height];
		drawScreen(gl);

	blurFrom = blurFboV.color[0];

	blurFboH2.bind();
		blurShaderH.bind();
		blurShaderH.uniforms.srcTex = toTex.bind();
		blurShaderH.uniforms.step = [1.0/shell.width,1.0/shell.height];
		drawScreen(gl);

	blurFboV2.bind();
		blurShaderV.bind();
		blurShaderV.uniforms.srcTex = blurFboH2.color[0].bind();
		blurShaderV.uniforms.step = [1.0/shell.width,1.0/shell.height];
		drawScreen(gl);
	
	blurTo = blurFboV2.color[0];

	blurTransition.uniforms.blurTo = blurTo;
	blurTransition.uniforms.blurFrom = blurFrom;
});
````

And then in my transition shader just mixing them together like so:

````
precision highp float;
uniform sampler2D from;
uniform sampler2D to;
uniform sampler2D blurFrom;
uniform sampler2D blurTo;
uniform float progress;
uniform vec2 resolution;


void main(){
	vec2 vUv = gl_FragCoord.xy / resolution.xy;
	float inv = 1.0 - progress;

	float doubleProg = clamp(progress*2.0,0.0,1.0);
	float doubleProgInv = 1.0 - doubleProg;

	float doubleInv = clamp(inv*2.0,0.0,1.0);
	float doubleInvInv = 1.0 - doubleInv;

	vec4 texTo = texture2D(to, vUv);
	vec4 texBlurTo = texture2D(blurTo, vec2(1.0) - vUv);

	vec4 texFrom = texture2D(from, vUv);
	vec4 texBlurFrom = texture2D(blurFrom, vec2(1.0) -vUv);


	vec4 blurFromTrans = texBlurFrom*doubleProg + texFrom*doubleProgInv;
	vec4 blurToTrans = texBlurTo*doubleInv + texTo*doubleInvInv;

	gl_FragColor = blurToTrans*progress + blurFromTrans*inv;
	gl_FragColor.a = 1.0;
}
````

Not sure if there is a better way but I suppose this would work. Could probably get away with only rendering the blur textures once if they are just still images and not video or a live webgl scene.

**Comment by gre** [comment]
I'm afraid it's not current possible in the "gl transition spec" that is just "one shader". You will have to continue writing this custom code.
Blur is a complex problem, especially complex to address it so it's a good quality while still efficient.
